CREATE TABLE IF NOT EXISTS picture_stats (
    id          BIGINT PRIMARY KEY AUTO_INCREMENT,
    pictureId   BIGINT NOT NULL UNIQUE COMMENT '图片ID',
    viewCount   BIGINT NOT NULL DEFAULT 0 COMMENT '查看次数',
    likeCount   BIGINT NOT NULL DEFAULT 0 COMMENT '点赞次数',
    collectCount BIGINT NOT NULL DEFAULT 0 COMMENT '收藏次数',
    downloadCount BIGINT NOT NULL DEFAULT 0 COMMENT '下载次数',
    shareCount  BIGINT NOT NULL DEFAULT 0 COMMENT '分享次数',
    impressionCount BIGINT NOT NULL DEFAULT 0 COMMENT '曝光次数',
    clickCount  BIGINT NOT NULL DEFAULT 0 COMMENT '点击次数',
    ctr         DECIMAL(10,6) DEFAULT 0 COMMENT '点击率',
    createTime  DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updateTime  DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_picture_id (pictureId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
